apiVersion: v1
kind: Service
metadata:
  name: spidercal-frontend-service
  namespace: spidercal-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 4200
      targetPort: 4200
  selector:
    app: spidercal-frontend
