apiVersion: v1
kind: Service
metadata:
  name: spidercal-backend-service
  namespace: spidercal-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spidercal-backend
