apiVersion: v1
kind: Service
metadata:
  name: spidercal-frontend-service
  namespace: spidercal-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: spidercal-frontend
